### ISSUE TITLE
Press release slug issue

### ISSUE THREAD

**Issue by leomanlapera** [leomanlapera/kfc#42]
I posted a press release over the weekend while Kyndall was out. The url looks good in browser, but when I copy it, there are extra characters.

https://global.kfc.com/press-release/KFC%E2%80%99S-LATEST-FATHER%E2%80%99S-DAY-CAMPAIGN-HAS-DADS-SMELLING-LIKE-A-WHOLE-SNACK

Have you seen this happen before? I looked at another article from late May with an apostrophe in url, and it shows/copies fine.

https://global.kfc.com/press-release/SOUTH-AFRICA'S-HUNGER-CRISIS-IT'S-NOT-JUST-ABOUT-FOOD

Could this be connected to the contentful transfer?

**Comment by karen-simplemedia** [comment]
Issue is now fixed.

PROBLEM:
The Slug field's Appearance was previously set to URL instead of Slug and so the Title entered does not encode properly

FIX:
Update the field's appearance to Slug and updated the slugs for the 2 press releases mentioned above so that there'll be no (') included in the URL

[SOUTH AFRICA'S HUNGER CRISIS– IT'S NOT JUST ABOUT FOOD!](https://app.contentful.com/spaces/h7j9u4fil4a3/entries/l82DFlo1m3NOjb1LhOeui)

[KFC’S LATEST FATHER’S DAY CAMPAIGN HAS DADS SMELLING LIKE A WHOLE SNACK!](https://app.contentful.com/spaces/h7j9u4fil4a3/entries/6XaLyNP4jcSOBqpGfRM1P7) - This still needs to be publish for the changes to the URL to take effect

**Comment by leomanlapera** [comment]
@nicolocarlo verified. this is now done.

**Comment by leomanlapera** [comment]
@karen-simplemedia thanks
